# Generated by Django 3.2.16 on 2022-11-21 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('region', models.TextField()),
                ('place', models.CharField(max_length=30)),
                ('like_users', models.ManyToManyField(related_name='like_qna', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(blank=True, to='tag.Tag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'qna',
                'verbose_name_plural': 'qna',
                'db_table': 'qna_board',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.qna')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
