# Generated by Django 3.2.16 on 2022-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='place',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
