# Generated by Django 3.2.13 on 2022-11-16 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qna',
            table='qna',
        ),
    ]
