# Generated by Django 3.2.13 on 2022-11-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20221116_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='tag',
            field=models.ManyToManyField(blank=True, to='qna.Tag', verbose_name='태그'),
        ),
    ]
