# Generated by Django 3.2.13 on 2022-11-16 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qna', '0004_alter_qna_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='like_users',
            field=models.ManyToManyField(related_name='like_qna', to=settings.AUTH_USER_MODEL),
        ),
    ]
