# Generated by Django 3.2.13 on 2022-11-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photospots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photospot',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
