# Generated by Django 3.2.13 on 2022-11-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='place',
            field=models.CharField(default='태초마을', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
