# Generated by Django 3.2.13 on 2022-11-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
