# Generated by Django 3.2.16 on 2022-11-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='thumbnail',
        ),
    ]
