# Generated by Django 3.2.13 on 2022-11-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='end_at',
            field=models.DateField(null=True),
        ),
    ]
