# Generated by Django 3.2.16 on 2022-11-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friend_people_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='people_number',
            field=models.PositiveIntegerField(),
        ),
    ]
