# Generated by Django 3.2.13 on 2022-11-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=1, null=True, unique=True),
        ),
    ]
