# Generated by Django 3.2.13 on 2022-11-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naver_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
